package model;

import java.util.UUID;

import model.common.AppModule;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 10 12:18:50 CEST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    
    public void createSavePoint(String customer) {
        System.out.println("----PROVA---: "+customer);
        System.out.println("createSavePoint");
        String uniqueID = "";
        uniqueID = UUID.randomUUID().toString();
        if (uniqueID != null) {
            insertSavePoint(uniqueID);
        }
    }
    
    public void insertSavePoint(String id) {
        ViewObject vo = findViewObject("SavepointTableView1");

        Row row = vo.createRow();
        row.setAttribute("IdSavepoint", id);
        row.setAttribute("NameSavepoint", "Franco");

        vo.insertRow(row);
        getDBTransaction().commit();
    }

    /**
     * Container's getter for SavepointTableView1.
     * @return SavepointTableView1
     */
    public ViewObjectImpl getSavepointTableView1() {
        return (ViewObjectImpl) findViewObject("SavepointTableView1");
    }

}

