package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 10 12:22:50 CEST 2023
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {

    void createSavePoint(String customer);
}

